# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# install:
# pre-commit install
#
# run:
# pre-comit run --all-files
#
# debug run:
# PCT_LOG=trace pre-commit run -a


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-symlinks
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: debug-statements
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: fix-byte-order-marker
    -   id: forbid-new-submodules
    -   id: forbid-submodules
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
    -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.7
  hooks:
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck
#       args: ["--severity=warning"]  # Optionally only show errors and warnings
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.104.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_checkov
